// import{} from './index_1.js';
// import{} from './index_2.js';
// import{} from './index_3.js';
// import{} from './index_4.js';
// import{} from './index_5.js';
// import{} from './index_6.js';
// import{} from './index_7.js';
// import{} from './index_8.js';

let div = document.createElement('div');
div.className = 'conteiner';
document.body.prepend(div);
div.style.display = 'flex';
div.style.flexDirection = 'column';
div.style.justifyContent = 'center';
div.style.margin = '20px';

let div_01 = document.createElement('div');
div_01.className = 'task_1';
div.prepend(div_01);
div_01.style.display = 'flex';
div_01.style.alignItems = 'center';
div_01.style.flexDirection = 'column';
let div_01_exercise = document.createElement('div');
let div_01_inputData = document.createElement('div');
let div_01_result = document.createElement('div');
div_01.append(div_01_exercise);
div_01.append(div_01_inputData);
div_01.append(div_01_result);
div_01_exercise.innerHTML = '<h3>Задание 1</h3>';
div_01_inputData.innerHTML = '<h4>Входные данные:</h4> <p>Дан объект obj с ключами: Минск, Москва, Киев, с элементами: Беларусь, Россия, Украина.</p>';
div_01_result.innerHTML = '<h4>Результат:</h4>';
div_01_exercise.style.display = 'flex';
div_01_inputData.style.display = 'flex';
div_01_result.style.display = 'flex';
div_01_exercise.style.alignItems = 'center';
div_01_inputData.style.alignItems = 'center';
div_01_result.style.alignItems = 'center';
div_01_exercise.style.flexDirection = 'column';
div_01_inputData.style.flexDirection = 'column';
div_01_result.style.flexDirection = 'column';

let div_02 = document.createElement('div');
div_02.className = 'task_2';
div.append(div_02);
div_02.style.display = 'flex';
div_02.style.alignItems = 'center';
div_02.style.flexDirection = 'column';
let div_02_exercise = document.createElement('div');
let div_02_result = document.createElement('div');
div_02.append(div_02_exercise);
div_02.append(div_02_result);
div_02_exercise.innerHTML = '<h3>Задание 2</h3>';
div_02_result.innerHTML = '<h4>Результат:</h4>';
div_02_exercise.style.display = 'flex';
div_02_result.style.display = 'flex';
div_02_exercise.style.alignItems = 'center';
div_02_result.style.alignItems = 'center';
div_02_exercise.style.flexDirection = 'column';
div_02_result.style.flexDirection = 'column';

let div_03 = document.createElement('div');
div_03.className = 'task_3';
div.append(div_03);
div_03.style.display = 'flex';
div_03.style.alignItems = 'center';
div_03.style.flexDirection = 'column';
let div_03_exercise = document.createElement('div');
let div_03_inputData = document.createElement('div');
let div_03_result = document.createElement('div');
div_03.append(div_03_exercise);
div_03.append(div_03_inputData);
div_03.append(div_03_result);
div_03_exercise.innerHTML = '<h3>Задание 3</h3>';
div_03_inputData.innerHTML = '<h4>Входные данные:</h4> <p>vegetables = ["Капуста", "Репа", "Редиска", "Морковка"];</p>';
div_03_result.innerHTML = '<h4>Результат:</h4>';
div_03_exercise.style.display = 'flex';
div_03_inputData.style.display = 'flex';
div_03_result.style.display = 'flex';
div_03_exercise.style.alignItems = 'center';
div_03_inputData.style.alignItems = 'center';
div_03_result.style.alignItems = 'center';
div_03_exercise.style.flexDirection = 'column';
div_03_inputData.style.flexDirection = 'column';
div_03_result.style.flexDirection = 'column';

let div_04 = document.createElement('div');
div_04.className = 'task_4';
div.append(div_04);
div_04.style.display = 'flex';
div_04.style.alignItems = 'center';
div_04.style.flexDirection = 'column';
let div_04_exercise = document.createElement('div');
let div_04_result = document.createElement('div');
div_04.append(div_04_exercise);
div_04.append(div_04_result);
div_04_exercise.innerHTML = '<h3>Задание 4</h3>';
div_04_result.innerHTML = '<h4>Результат:</h4>';
div_04_exercise.style.display = 'flex';
div_04_result.style.display = 'flex';
div_04_exercise.style.alignItems = 'center';
div_04_result.style.alignItems = 'center';
div_04_exercise.style.flexDirection = 'column';
div_04_result.style.flexDirection = 'column';

let div_05 = document.createElement('div');
div_05.className = 'task_5';
div.append(div_05);
div_05.style.display = 'flex';
div_05.style.alignItems = 'center';
div_05.style.flexDirection = 'column';
let div_05_exercise = document.createElement('div');
let div_05_result = document.createElement('div');
div_05.append(div_05_exercise);
div_05.append(div_05_result);
div_05_exercise.innerHTML = '<h3>Задание 5</h3>';
div_05_result.innerHTML = '<h4>Результат:</h4>';
div_05_exercise.style.display = 'flex';
div_05_result.style.display = 'flex';
div_05_exercise.style.alignItems = 'center';
div_05_result.style.alignItems = 'center';
div_05_exercise.style.flexDirection = 'column';
div_05_result.style.flexDirection = 'column';

let div_06 = document.createElement('div');
div_06.className = 'task_6';
div.append(div_06);
div_06.style.display = 'flex';
div_06.style.alignItems = 'center';
div_06.style.flexDirection = 'column';
let div_06_exercise = document.createElement('div');
let div_06_result = document.createElement('div');
div_06.append(div_06_exercise);
div_06.append(div_06_result);
div_06_exercise.innerHTML = '<h3>Задание 6</h3>';
div_06_result.innerHTML = '<h4>Результат:</h4>';
div_06_exercise.style.display = 'flex';
div_06_result.style.display = 'flex';
div_06_exercise.style.alignItems = 'center';
div_06_result.style.alignItems = 'center';
div_06_exercise.style.flexDirection = 'column';
div_06_result.style.flexDirection = 'column';

let div_07 = document.createElement('div');
div_07.className = 'task_7';
div.append(div_07);
div_07.style.display = 'flex';
div_07.style.alignItems = 'center';
div_07.style.flexDirection = 'column';
let div_07_exercise = document.createElement('div');
let div_07_inputData = document.createElement('div');
let div_07_result = document.createElement('div');
div_07.append(div_07_exercise);
div_07.append(div_07_inputData);
div_07.append(div_07_result);
div_07_exercise.innerHTML = '<h3>Задание 7</h3>';
div_07_inputData.innerHTML = '<h4>Входные данные:</h4> <p>const arr = ["php", "php", "css", "css", "script", "script", "html", "html", "java"];</p>';
div_07_result.innerHTML = '<h4>Результат:</h4>';
div_07_exercise.style.display = 'flex';
div_07_inputData.style.display = 'flex';
div_07_result.style.display = 'flex';
div_07_exercise.style.alignItems = 'center';
div_07_inputData.style.alignItems = 'center';
div_07_result.style.alignItems = 'center';
div_07_exercise.style.flexDirection = 'column';
div_07_inputData.style.flexDirection = 'column';
div_07_result.style.flexDirection = 'column';

let div_08 = document.createElement('div');
div_08.className = 'task_8';
div.append(div_08);
div_08.style.display = 'flex';
div_08.style.alignItems = 'center';
div_08.style.flexDirection = 'column';
let div_08_exercise = document.createElement('div');
let div_08_inputData = document.createElement('div');
let div_08_result = document.createElement('div');
div_08.append(div_08_exercise);
div_08.append(div_08_inputData);
div_08.append(div_08_result);
div_08_exercise.innerHTML = '<h3>Задание 8</h3>';
div_08_inputData.innerHTML = '<h4>Входные данные:</h4> <p>const array1 = [5, 2, 1, -10, 8];</p><p>const array2 = [5, 2, 1, -9, 3, 7];</p>';
div_08_result.innerHTML = '<h4>Результат:</h4>';
div_08_exercise.style.display = 'flex';
div_08_inputData.style.display = 'flex';
div_08_result.style.display = 'flex';
div_08_exercise.style.alignItems = 'center';
div_08_inputData.style.alignItems = 'center';
div_08_result.style.alignItems = 'center';
div_08_exercise.style.flexDirection = 'column';
div_08_inputData.style.flexDirection = 'column';
div_08_result.style.flexDirection = 'column';

